blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/arch-go/arch-go/discussions
    about: Please share and discuss ideas, ask and answer questions here.